apiVersion: batch/v1
kind: Job
metadata:
  name: spark-etl
  namespace: hasu-ml
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: spark-etl
        image: annduke/hasu-spark-etl:v23  # Image từ spark/custom_image
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: hasu-ml-secrets
        resources:
          requests: {cpu: "2", memory: "4Gi"}
          limits: {cpu: "4", memory: "8Gi"}
        volumeMounts:
        - name: csv-input
          mountPath: /csv_input
        - name: csv-output
          mountPath: /csv_output
        command: ["python3"]
        args: ["/opt/spark/work-dir/spark_etl_full.py"]
      volumes:
      - name: csv-input
        persistentVolumeClaim:
          claimName: csv-input-pvc
      - name: csv-output
        persistentVolumeClaim:
          claimName: csv-output-pvc
