apiVersion: batch/v1
kind: Job
metadata:
  name: spark-etl
  namespace: hasu-ml
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: spark-etl
        image: annduke/hasu-spark-etl:real-final-v19
        imagePullPolicy: Always
        command: ["python3"]
        args: ["/opt/spark/python_etl/etl_main.py"]
        env:
        - name: JAVA_HOME
          value: "/usr/lib/jvm/java-21-openjdk-amd64"
        envFrom:
        - secretRef:
            name: hasu-ml-secrets
        resources:
          requests: {cpu: "2", memory: "4Gi"}
          limits: {cpu: "4", memory: "8Gi"}
        volumeMounts:
        - name: csv-input
          mountPath: /csv_input
        - name: csv-output
          mountPath: /csv_output
      volumes:
      - name: csv-input
        persistentVolumeClaim:
          claimName: csv-input-pvc
      - name: csv-output
        persistentVolumeClaim:
          claimName: csv-output-pvc
