apiVersion: batch/v1
kind: Job
metadata:
  name: spark-etl
  namespace: hasu-ml
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      # Chạy trên node có dữ liệu CSV
      nodeSelector:
        kubernetes.io/hostname: k3s-master
      restartPolicy: Never
      containers:
      - name: spark-etl
        image: annduke/hasu-spark-etl:real-final-v26
        imagePullPolicy: IfNotPresent
        command: ["python3"]
        args: ["/opt/spark/python_etl/etl_main.py"]
        env:
        - name: JAVA_HOME
          value: "/usr/lib/jvm/java-21-openjdk-amd64"
        envFrom:
        - secretRef:
            name: hasu-ml-secrets
        resources:
          requests: {cpu: "2", memory: "4Gi"}
          limits: {cpu: "4", memory: "8Gi"}
        volumeMounts:
        - name: csv-data
          mountPath: /csv_input
      volumes:
      # Mount trực tiếp thư mục chứa CSV từ host
      - name: csv-data
        hostPath:
          path: /home/hasu/actions-runner/_work/API_ETL_XGBoost/API_ETL_XGBoost/csv_input
          type: Directory
