apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csv-input-pvc
  namespace: hasu-ml
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csv-output-pvc
  namespace: hasu-ml
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
