apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-models
  namespace: hasu-ml
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 20Gi
