apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csv-input-pvc
  namespace: hasu-ml
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csv-processed-pvc
  namespace: hasu-ml
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
