version: 2
sources:
  - name: retail_source
    database: "{{ env_var('CLICKHOUSE_DB', 'retail_dw') }}"
    schema: "{{ env_var('CLICKHOUSE_DB', 'retail_dw') }}"
    tables:
      - name: raw_products
      - name: raw_branches  
      - name: raw_transactions
      - name: raw_transaction_details
