retail_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'retail_user') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'retail_password') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'retail_db') }}"
      schema: staging
      threads: 4

    prod:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'retail_user') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'retail_password') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'retail_db') }}"
      schema: marts
      threads: 8

    clickhouse:
      type: clickhouse
      host: "{{ env_var('CLICKHOUSE_HOST', 'localhost') }}"
      port: "{{ env_var('CLICKHOUSE_PORT', '8123') | int }}"
      user: "{{ env_var('CLICKHOUSE_USER', 'default') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD', 'clickhouse_password') }}"
      database: "{{ env_var('CLICKHOUSE_DB', 'retail_dw') }}"
      schema: default
      threads: 4

